function generate_run_script(num_nodes, account_name, user_name, filename, target_year)
    % Generate the auto-restarting Expanse SLURM batch script.
    %
    % Default usage from the experiment scripts:
    %   generate_run_script(node_num, account, user_name)
    %
    % Optional:
    %   generate_run_script(node_num, account, user_name, 'run_roms_auto', 2009)

    if nargin < 4 || isempty(filename)
        filename = 'run_roms_auto';
    end

    if nargin < 5 || isempty(target_year)
        target_year = 2009;
    end

    if isnumeric(target_year)
        target_year_text = sprintf('%04d', target_year);
    else
        target_year_text = char(target_year);
    end

    if isempty(regexp(target_year_text, '^[0-9]{4}$', 'once'))
        error('target_year must be a four-digit year.');
    end

    num_tasks = num_nodes * 128;

    fid = fopen(filename, 'w');
    if fid < 0
        error('Could not open "%s" for writing.', filename);
    end
    cleaner = onCleanup(@() fclose(fid));

    write_line(fid, '#!/bin/bash');
    write_line(fid, '#SBATCH --job-name="roms_auto"');
    write_line(fid, '');
    write_line(fid, '# %j=job_number and %N gives nodelist output="wec_real.%j.%N.out"');
    write_line(fid, '#SBATCH --output="log.%j.%N.log"');
    write_line(fid, '');
    write_line(fid, '# Can only use a max of 32 nodes on ''compute'' partition:');
    write_line(fid, '#SBATCH --partition=compute');
    fprintf(fid, '#SBATCH --nodes=%d\n\n', num_nodes);
    write_line(fid, '# Request number of cores (Expanse has 128 cores per node)');
    write_line(fid, '#SBATCH --ntasks-per-node=128');
    fprintf(fid, '#SBATCH --account=%s\n', account_name);
    write_line(fid, '#SBATCH --export=ALL');
    write_line(fid, '');
    write_line(fid, '# Max run time is 48 hours. Ask Slurm for a signal before the limit so the');
    write_line(fid, '# next job can be queued even if this run is about to be stopped.');
    write_line(fid, '#SBATCH -t 48:00:00');
    write_line(fid, '#SBATCH --signal=B:USR1@600');
    write_line(fid, '');
    write_line(fid, '# Email notifications:');
    fprintf(fid, '#SBATCH --mail-user=%s\n', user_name);
    write_line(fid, '#SBATCH --mail-type=ALL');
    write_line(fid, '');
    write_line(fid, '#-----------------------------------------------------------------');
    write_line(fid, '');
    write_line(fid, 'set -euo pipefail');
    write_line(fid, '');
    write_line(fid, '# Stop once the newest neptune_rst.YYYYMMDDhhmmss[.rank].nc restart set has');
    write_line(fid, '# reached this calendar year. Override at submit time, for example:');
    write_line(fid, '#   sbatch --export=ALL,TARGET_YEAR=2035 run_roms_auto');
    fprintf(fid, 'TARGET_YEAR="${TARGET_YEAR:-%s}"\n', target_year_text);
    write_line(fid, '');
    write_line(fid, 'INPUT_FILE="${INPUT_FILE:-neptune.in}"');
    write_line(fid, 'RESTART_PREFIX="${RESTART_PREFIX:-neptune_rst}"');
    fprintf(fid, 'NTASKS="${SLURM_NTASKS:-%d}"\n', num_tasks);
    write_line(fid, 'SCRIPT_NAME="${SCRIPT_NAME:-run_roms_auto}"');
    write_line(fid, 'BACKUP_DIR="${BACKUP_DIR:-backup}"');
    write_line(fid, '');
    write_line(fid, 'if ! [[ "${TARGET_YEAR}" =~ ^[0-9]{4}$ ]]; then');
    write_line(fid, '  echo "ERROR: TARGET_YEAR must be a four-digit year, got ''${TARGET_YEAR}''." >&2');
    write_line(fid, '  exit 2');
    write_line(fid, 'fi');
    write_line(fid, '');
    write_line(fid, 'source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"');
    write_line(fid, 'experiment_dir=""');
    write_line(fid, '');
    write_line(fid, 'for candidate_dir in "${SLURM_SUBMIT_DIR:-}" "${PWD}" "${source_dir}"; do');
    write_line(fid, '  [[ -n "${candidate_dir}" ]] || continue');
    write_line(fid, '  if [[ -f "${candidate_dir}/${INPUT_FILE}" && -d "${candidate_dir}/Neptune_input" ]]; then');
    write_line(fid, '    experiment_dir="$(cd "${candidate_dir}" && pwd -P)"');
    write_line(fid, '    break');
    write_line(fid, '  fi');
    write_line(fid, 'done');
    write_line(fid, '');
    write_line(fid, 'if [[ -z "${experiment_dir}" ]]; then');
    write_line(fid, '  echo "ERROR: could not locate the experiment directory." >&2');
    write_line(fid, '  echo "       Expected to find ${INPUT_FILE} and Neptune_input/." >&2');
    write_line(fid, '  echo "       SLURM_SUBMIT_DIR=${SLURM_SUBMIT_DIR:-unset}" >&2');
    write_line(fid, '  echo "       PWD=${PWD}" >&2');
    write_line(fid, '  echo "       script source dir=${source_dir}" >&2');
    write_line(fid, '  exit 2');
    write_line(fid, 'fi');
    write_line(fid, '');
    write_line(fid, 'SCRIPT_DIR="${experiment_dir}"');
    write_line(fid, 'SCRIPT_PATH="${SCRIPT_DIR}/${SCRIPT_NAME}"');
    write_line(fid, '');
    write_line(fid, 'if [[ ! -f "${SCRIPT_PATH}" ]]; then');
    write_line(fid, '  echo "ERROR: cannot find ${SCRIPT_PATH} for automatic resubmission." >&2');
    write_line(fid, '  echo "       Submit this job from the experiment directory, or set SCRIPT_NAME." >&2');
    write_line(fid, '  exit 2');
    write_line(fid, 'fi');
    write_line(fid, '');
    write_line(fid, 'cd "${SCRIPT_DIR}"');
    write_line(fid, '');
    write_line(fid, 'latest_restart_file() {');
    write_line(fid, '  local latest=""');
    write_line(fid, '  local latest_index=""');
    write_line(fid, '  local rst base rest index suffix rank');
    write_line(fid, '');
    write_line(fid, '  shopt -s nullglob');
    write_line(fid, '  for rst in ./"${RESTART_PREFIX}".*.nc; do');
    write_line(fid, '    base="${rst##*/}"');
    write_line(fid, '    rest="${base#${RESTART_PREFIX}.}"');
    write_line(fid, '    index="${rest%%.*}"');
    write_line(fid, '    suffix="${rest#${index}.}"');
    write_line(fid, '');
    write_line(fid, '    [[ "${index}" =~ ^[0-9]{14}$ ]] || continue');
    write_line(fid, '    if [[ "${suffix}" != "nc" ]]; then');
    write_line(fid, '      rank="${suffix%.nc}"');
    write_line(fid, '      [[ "${rank}" =~ ^[0-9]{3}$ ]] || continue');
    write_line(fid, '    fi');
    write_line(fid, '');
    write_line(fid, '    if [[ -z "${latest_index}" || "${index}" > "${latest_index}" ]]; then');
    write_line(fid, '      latest_index="${index}"');
    write_line(fid, '      latest="./${RESTART_PREFIX}.${index}.nc"');
    write_line(fid, '    fi');
    write_line(fid, '  done');
    write_line(fid, '  shopt -u nullglob');
    write_line(fid, '');
    write_line(fid, '  printf ''%s\n'' "${latest}"');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'restart_index() {');
    write_line(fid, '  local base index');
    write_line(fid, '  base="${1##*/}"');
    write_line(fid, '  index="${base#${RESTART_PREFIX}.}"');
    write_line(fid, '  index="${index%%.*}"');
    write_line(fid, '  printf ''%s\n'' "${index}"');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'target_reached() {');
    write_line(fid, '  local latest index year');
    write_line(fid, '  latest="$(latest_restart_file)"');
    write_line(fid, '');
    write_line(fid, '  [[ -n "${latest}" ]] || return 1');
    write_line(fid, '');
    write_line(fid, '  index="$(restart_index "${latest}")"');
    write_line(fid, '  year="${index:0:4}"');
    write_line(fid, '');
    write_line(fid, '  (( 10#${year} >= 10#${TARGET_YEAR} ))');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'backup_old_restart_files() {');
    write_line(fid, '  local latest latest_index rst base rest index suffix rank dest');
    write_line(fid, '');
    write_line(fid, '  latest="$(latest_restart_file)"');
    write_line(fid, '  if [[ -z "${latest}" ]]; then');
    write_line(fid, '    echo "No restart files found; skipping restart backup cleanup."');
    write_line(fid, '    return 0');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  latest_index="$(restart_index "${latest}")"');
    write_line(fid, '  mkdir -p "${BACKUP_DIR}"');
    write_line(fid, '');
    write_line(fid, '  shopt -s nullglob');
    write_line(fid, '  for rst in ./"${RESTART_PREFIX}".*.nc; do');
    write_line(fid, '    base="${rst##*/}"');
    write_line(fid, '    rest="${base#${RESTART_PREFIX}.}"');
    write_line(fid, '    index="${rest%%.*}"');
    write_line(fid, '    suffix="${rest#${index}.}"');
    write_line(fid, '');
    write_line(fid, '    [[ "${index}" =~ ^[0-9]{14}$ ]] || continue');
    write_line(fid, '    if [[ "${suffix}" != "nc" ]]; then');
    write_line(fid, '      rank="${suffix%.nc}"');
    write_line(fid, '      [[ "${rank}" =~ ^[0-9]{3}$ ]] || continue');
    write_line(fid, '    fi');
    write_line(fid, '    [[ "${index}" != "${latest_index}" ]] || continue');
    write_line(fid, '');
    write_line(fid, '    dest="${BACKUP_DIR}/${base}"');
    write_line(fid, '    if [[ -e "${dest}" ]]; then');
    write_line(fid, '      echo "Backup already contains ${dest}; leaving ${rst} in place."');
    write_line(fid, '      continue');
    write_line(fid, '    fi');
    write_line(fid, '');
    write_line(fid, '    echo "Moving old restart ${rst} to ${BACKUP_DIR}/."');
    write_line(fid, '    mv "${rst}" "${BACKUP_DIR}/"');
    write_line(fid, '  done');
    write_line(fid, '  shopt -u nullglob');
    write_line(fid, '');
    write_line(fid, '  echo "Kept latest restart set in the run directory: ${latest}"');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'update_initial_file() {');
    write_line(fid, '  local input_file="$1"');
    write_line(fid, '  local restart_file="$2"');
    write_line(fid, '  local tmp_file="${input_file}.tmp.$$"');
    write_line(fid, '');
    write_line(fid, '  if [[ ! -f "${input_file}.initial" ]]; then');
    write_line(fid, '    cp -p "${input_file}" "${input_file}.initial"');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  if awk -v rst="${restart_file}" ''');
    write_line(fid, '    BEGIN {');
    write_line(fid, '      state = 0');
    write_line(fid, '      changed = 0');
    write_line(fid, '    }');
    write_line(fid, '    /^[[:space:]]*initial:[[:space:]]+NRREC[[:space:]]+filename[[:space:]]*$/ {');
    write_line(fid, '      state = 1');
    write_line(fid, '      print');
    write_line(fid, '      next');
    write_line(fid, '    }');
    write_line(fid, '    state == 1 {');
    write_line(fid, '      print');
    write_line(fid, '      state = 2');
    write_line(fid, '      next');
    write_line(fid, '    }');
    write_line(fid, '    state == 2 {');
    write_line(fid, '      print "     " rst');
    write_line(fid, '      state = 0');
    write_line(fid, '      changed++');
    write_line(fid, '      next');
    write_line(fid, '    }');
    write_line(fid, '    {');
    write_line(fid, '      print');
    write_line(fid, '    }');
    write_line(fid, '    END {');
    write_line(fid, '      if (changed != 1) {');
    write_line(fid, '        exit 2');
    write_line(fid, '      }');
    write_line(fid, '    }');
    write_line(fid, '  '' "${input_file}" > "${tmp_file}"; then');
    write_line(fid, '    mv "${tmp_file}" "${input_file}"');
    write_line(fid, '  else');
    write_line(fid, '    rm -f "${tmp_file}"');
    write_line(fid, '    echo "ERROR: could not update the initial-condition filename in ${input_file}." >&2');
    write_line(fid, '    exit 2');
    write_line(fid, '  fi');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'resubmit_requested=0');
    write_line(fid, '');
    write_line(fid, 'submit_next_job() {');
    write_line(fid, '  local reason="$1"');
    write_line(fid, '  local latest');
    write_line(fid, '  local -a dependency_arg=()');
    write_line(fid, '');
    write_line(fid, '  if (( resubmit_requested == 1 )); then');
    write_line(fid, '    echo "Continuation job already submitted; skipping duplicate request (${reason})."');
    write_line(fid, '    return 0');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  latest="$(latest_restart_file)"');
    write_line(fid, '  if [[ -z "${latest}" ]]; then');
    write_line(fid, '    echo "No restart file was found; cannot safely submit a continuation job." >&2');
    write_line(fid, '    return 1');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  if target_reached; then');
    write_line(fid, '    echo "Target year ${TARGET_YEAR} has been reached by ${latest}; not resubmitting."');
    write_line(fid, '    return 0');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  resubmit_requested=1');
    write_line(fid, '  if [[ -n "${SLURM_JOB_ID:-}" ]]; then');
    write_line(fid, '    dependency_arg=(--dependency="afterany:${SLURM_JOB_ID}")');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  echo "Submitting continuation job (${reason}) from latest restart ${latest}."');
    write_line(fid, '  sbatch "${dependency_arg[@]}" "${SCRIPT_PATH}"');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'handle_walltime_signal() {');
    write_line(fid, '  echo "Received Slurm pre-time-limit signal at $(date)."');
    write_line(fid, '  submit_next_job "pre-time-limit signal" || true');
    write_line(fid, '}');
    write_line(fid, '');
    write_line(fid, 'trap handle_walltime_signal USR1');
    write_line(fid, '');
    write_line(fid, 'echo "Target restart year: ${TARGET_YEAR}"');
    write_line(fid, 'latest_restart="$(latest_restart_file)"');
    write_line(fid, '');
    write_line(fid, 'if [[ -n "${latest_restart}" ]]; then');
    write_line(fid, '  latest_index="$(restart_index "${latest_restart}")"');
    write_line(fid, '  echo "Latest restart before run: ${latest_restart} (${latest_index})"');
    write_line(fid, '');
    write_line(fid, '  if target_reached; then');
    write_line(fid, '    echo "Target year ${TARGET_YEAR} is already reached; exiting."');
    write_line(fid, '    backup_old_restart_files');
    write_line(fid, '    exit 0');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  update_initial_file "${INPUT_FILE}" "${latest_restart}"');
    write_line(fid, '  echo "Updated ${INPUT_FILE} to restart from ${latest_restart}."');
    write_line(fid, '  backup_old_restart_files');
    write_line(fid, 'else');
    write_line(fid, '  echo "No restart file found; using the existing initial-condition entry in ${INPUT_FILE}."');
    write_line(fid, 'fi');
    write_line(fid, '');
    write_line(fid, '# MVAPICH2 flags:');
    write_line(fid, 'export MV2_USE_RDMA_CM=0');
    write_line(fid, 'export MV2_IBA_HCA=mlx5_2');
    write_line(fid, 'export MV2_DEFAULT_PORT=1');
    write_line(fid, '');
    write_line(fid, 'module purge');
    write_line(fid, 'module load slurm');
    write_line(fid, 'module load cpu/0.15.4  intel/19.1.1.217  mvapich2/2.3.4');
    write_line(fid, 'module load netcdf-c/4.7.4');
    write_line(fid, 'module load netcdf-fortran/4.5.3');
    write_line(fid, '');
    write_line(fid, 'cd Neptune_input/');
    write_line(fid, 'sh do_partit.sh');
    write_line(fid, 'cd ..');
    write_line(fid, 'make');
    write_line(fid, '');
    write_line(fid, 'srun --mpi=pmi2 -n "${NTASKS}" roms "${INPUT_FILE}" &');
    write_line(fid, 'roms_pid=$!');
    write_line(fid, '');
    write_line(fid, 'while true; do');
    write_line(fid, '  set +e');
    write_line(fid, '  wait "${roms_pid}"');
    write_line(fid, '  roms_status=$?');
    write_line(fid, '  set -e');
    write_line(fid, '');
    write_line(fid, '  if kill -0 "${roms_pid}" 2>/dev/null; then');
    write_line(fid, '    continue');
    write_line(fid, '  fi');
    write_line(fid, '');
    write_line(fid, '  break');
    write_line(fid, 'done');
    write_line(fid, '');
    write_line(fid, 'if (( roms_status == 0 )); then');
    write_line(fid, '  backup_old_restart_files');
    write_line(fid, '  submit_next_job "normal completion"');
    write_line(fid, 'else');
    write_line(fid, '  echo "ROMS exited with status ${roms_status}; not submitting a new job unless one was already queued by the signal handler." >&2');
    write_line(fid, '  exit "${roms_status}"');
    write_line(fid, 'fi');

    clear cleaner

    fprintf('Auto-restarting SLURM batch script written to "%s"\n', filename);
end

function write_line(fid, line)
    fprintf(fid, '%s\n', line);
end
